<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5c2ed4ffa9285',
	'title' => 'Block: Fullwidth',
	'fields' => array(
		array(
			'key' => 'field_5c2f1268ce3ae',
			'label' => 'Content',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c2ed634eb5f7',
			'label' => 'Content',
			'name' => 'content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_5c2f276a77df9',
			'label' => 'Smart center align',
			'name' => 'smart_center_align',
			'type' => 'true_false',
			'instructions' => 'Center align on desktop, left align on mobile (can be overridden with the editor alignment controls)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c2f118a98a10',
			'label' => 'Settings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c2fdf30ef7e5',
			'label' => 'Layout',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 1,
			'multi_expand' => 1,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c2f201c2670a',
			'label' => 'Use layout defaults',
			'name' => 'use_layout_defaults',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c2f0c882bec1',
			'label' => 'Maximum content width',
			'name' => 'content_width',
			'type' => 'range',
			'instructions' => 'The maximum width in pixels of the inner content',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f201c2670a',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33.333333',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 400,
			'max' => 1400,
			'step' => 10,
			'prepend' => '',
			'append' => 'px',
		),
		array(
			'key' => 'field_5c2f1100e24f4',
			'label' => 'Padding top',
			'name' => 'padding_top',
			'type' => 'range',
			'instructions' => 'Override the top padding (desktop only)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f201c2670a',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33.333333',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => 200,
			'step' => 10,
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5c2f1137e24f5',
			'label' => 'Padding bottom',
			'name' => 'padding_bottom',
			'type' => 'range',
			'instructions' => 'Override the top padding (desktop only)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2f201c2670a',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33.333333',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => 200,
			'step' => 10,
			'prepend' => '',
			'append' => 'px',
		),
		array(
			'key' => 'field_5c2f11be98a11',
			'label' => 'Layout (end)',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 1,
		),
		array(
			'key' => 'field_5c2f11cb98a12',
			'label' => 'Color & Background',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 1,
			'multi_expand' => 1,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5c2ef9e653ede',
			'label' => 'Background image',
			'name' => 'background_image',
			'type' => 'image',
			'instructions' => 'An optional background image',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3333',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg',
		),
		array(
			'key' => 'field_5c2f0d022bec2',
			'label' => 'Background color',
			'name' => 'background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3333',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5c2efa4453ee1',
			'label' => 'Text color',
			'name' => 'text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3333',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5c2f3595f5b0c',
			'label' => 'Background color opacity',
			'name' => 'background_color_opacity',
			'type' => 'range',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2ef9e653ede',
						'operator' => '!=empty',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => 100,
			'step' => '',
			'prepend' => '',
			'append' => '% opacity',
		),
		array(
			'key' => 'field_5c2f11f198a13',
			'label' => 'Color & Background (end)',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/fullwidth',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'A fullwidth section',
));

endif;